export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
export const FAILED = 'FAILED';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const PROFILE_BRIEF_LOADED = 'PROFILE_BRIEF_LOADED';
export const SERVICE_BRIEF_LOADED = 'SERVICE_BRIEF_LOADED';

export const AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const OVERLAY_SHOW_SIGNOUT = 'OVERLAY_SHOW_SIGNOUT';
export const OVERLAY_HIDE_SIGNOUT = 'OVERLAY_HIDE_SIGNOUT';

export const OVERLAY_SHOW_RATING = 'OVERLAY_SHOW_RATING';
export const OVERLAY_HIDE_RATING = 'OVERLAY_HIDE_RATING';

export const CORE_BUSINESS_LOADED = 'CORE_BUSINESS_LOADED';

export const PACKAGE_GROUP_LOADED = 'PACKAGE_GROUP_LOADED';


export const BASE_TIMEZONE_CHANGES = 'BASE_TIMEZONE_CHANGES';
export const CALENDAR_SETTING_UPDATED = 'CALENDAR_SETTING_UPDATED';

export const NOTIFICATION_UPDATED = 'NOTIFICATION_UPDATED';
export const PROFILE_LOADED = 'PROFILE_LOADED';
export const FAVORITE_UPDATED = 'FAVORITE_UPDATED';
export const FAVORITE_LOADED = 'FAVORITE_LOADED';
export const BUSINESS_TYPES_LOADED = 'BUSINESS_TYPES_LOADED';
export const BUSINESS_TYPES_SELECT = 'BUSINESS_TYPES_SELECT';
export const PROFILE_UPDATED = 'PROFILE_UPDATED';
export const AVATAR_UPDATED = 'AVATAR_UPDATED';
export const PROFILE_GENERATED_QR = 'PROFILE_GENERATED_QR';
export const PROFILE_VERIFIED = 'PROFILE_VERIFIED';
export const SUBDOMAIN_VALIDATE = 'SUBDOMAIN_VALIDATE';

export const GALLERY_PHOTO_LOADED = 'GALLERY_PHOTO_LOADED';
export const GALLERY_PHOTO_UPLOADED = 'GALLERY_PHOTO_UPLOADED';
export const GALLERY_PHOTO_SELECTED = 'GALLERY_PHOTO_SELECTED';
export const GALLERY_PHOTO_DELETED = 'GALLERY_PHOTO_DELETED';
export const STOP_LOADING_FOR_TIMESLOT = 'STOP_LOADING_FOR_TIMESLOT';
export const SEARCH_FAILED = 'SEARCH_FAILED';
export const SEARCH_LOADED = 'SEARCH_LOADED';
export const SEARCH_EMBED_BOX1_LOADED = 'SEARCH_EMBED_BOX1_LOADED';

export const SEARCH_DATESLOT_LOADED = 'SEARCH_DATESLOT_LOADED';
export const SEARCH_TIMESLOT_FOR_BOOKING_LOADED = 'SEARCH_TIMESLOT_FOR_BOOKING_LOADED';
export const SEARCH_PROFILE_LOADED = 'SEARCH_PROFILE_LOADED';
export const SEARCH_SERVICE_LOADED = 'SEARCH_SERVICE_LOADED';
export const SEARCH_SERVICE_SELECTED = 'SEARCH_SERVICE_SELECTED';
export const SEARCH_PROVIDER_SELECTED = 'SEARCH_PROVIDER_SELECTED';
export const SEARCH_DATESLOT_SELECTED = 'SEARCH_DATESLOT_SELECTED';
export const SEARCH_TIMESLOT_SELECTED = 'SEARCH_TIMESLOT_SELECTED';
export const SEARCH_TIMESLOT_LOADED = 'SEARCH_TIMESLOT_LOADED';
export const SEARCH_TIMESLOT_REMOVED = 'SEARCH_TIMESLOT_REMOVED';

export const SERVICE_STEP_CHANGED = 'SERVICE_STEP_CHANGED';
export const SERVICE_MEMBER_LOADED = 'SERVICE_MEMBER_LOADED';
export const SERVICE_MEMBER_FAILED = 'SERVICE_MEMBER_FAILED';
export const SERVICE_SHARED_SELECTED = 'SERVICE_SHARED_SELECTED';
export const TIMESLOT_RESERVATION_LOADED = 'TIMESLOT_RESERVATION_LOADED';
export const TIMESLOT_STATUS_UPDATED = 'TIMESLOT_STATUS_UPDATED';
export const TIMESLOT_SELECTED_VIEW = 'TIMESLOT_SELECTED_VIEW';
export const TIMESLOT_SELECTED_ROW = 'TIMESLOT_SELECTED_ROW';
export const TIMESLOT_UNSELECTED_ROW = 'TIMESLOT_UNSELECTED_ROW';
export const TIMESLOT_ABSENCE_GROUP = 'TIMESLOT_ABSENCE_GROUP';
export const RESERVATION_CANCELED = 'RESERVATION_CANCELED';
export const TIMESLOT_CANCELED_ROWS = 'TIMESLOT_CANCELED_ROWS';
export const TIMESLOT_EVENT_LOADED = 'TIMESLOT_EVENT_LOADED';
export const TIMESLOT_ON_SERVE_LOADED = 'TIMESLOT_ON_SERVE_LOADED';
export const TIMESLOT_FILTER_PROVIDER = 'TIMESLOT_FILTER_PROVIDER';
export const TIMESLOT_CLEAR_ERR = 'TIMESLOT_CLEAR_ERR';
export const TIMESLOT_SOCKET_UPDATED = 'TIMESLOT_SOCKET_UPDATED';
export const TIMESLOT_SOCKET_RECEIVED_CONFIRMED = 'TIMESLOT_SOCKET_RECEIVED_CONFIRMED';

export const BOOKING_PAYMENT_FAILED = 'BOOKING_PAYMENT_FAILED';

export const CLIENT_INVOICES_FAILED = 'CLIENT_INVOICES_FAILED';
export const CLIENT_INVOICES_LOADED = 'CLIENT_INVOICES_LOADED';


export const RATE_FAILED = 'RATE_FAILED';
export const RATE_LOADED = 'RATE_LOADED';


export const PAYMENT_REfID_LOADED = 'PAYMENT_REfID_LOADED';
export const PAYMENT_REfID_FAILED = 'PAYMENT_REfID_FAILED';
